version: "3.5"

services:
  mySQL-A:
    build: ./
    image: dockerfile
    container_name: "mysql-A"
    ports:
      - "3307:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql
  neo4j-A:
    image: neo4j
    container_name: "neo4j-A"
    environment:
      - NEO4J_AUTH:none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
     ### armazenamentod e dados do bd neo4j
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      ### diretorio de saida dos logs do neo4j